import type { StudentEventType, TeacherEventType } from 'Events'

export const TEACHER_EVENT_COLORS: Record<TeacherEventType, string> = {
  SCIENCE_POSTS: '#ED254E',
  TRAINEE_OR_QUALIFIER_HIGHER: '#F9DC5C',
  CONFERENCES_OR_APPROBATION: '#C2EABD',
  STUDENT_CONTEST_OR_OLYMPIAD: '#011936',
  SCHOOLBOY_CONTEST_OR_OLYMPIAD: '#465362',
  METHODICAL_DEVELOPMENT: '#DEE38D',
  BOOKS: '#F38155',
  DEFENSE_OR_SCIENCE_LEADERSHIP: '#24364C',
  PARTICIPATION_ON_COUNCILS: '#324E58',
  MANAGMENT_PROJECTS_AND_ETC: '#E9B271',
  PARTICIPATION_ON_EXPERT_COMMISIONS: '#D0E7A5',
  SCIENFIC_CONSULTING: '#1A3447',
  TEACHING_OTHER_LANGUAGE: '#2E0136',
  PARTICIPATION_ON_PEOPLE_AND_PROFF_ASSOCIATIONS: '#8DE3AB',
}

export const STUDENT_EVENT_COLORS: Record<StudentEventType, string> = {
  SCIENCE: '#ED254E',
  SPORT: '#E9B271',
  CULTURE: '#8DE3AB',
  PUBLIC: '#2E0136',
}
